/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqteam_ocrisk_API */

#ifndef _Included_org_sqteam_ocrisk_API
#define _Included_org_sqteam_ocrisk_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sqteam_ocrisk_API
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sqteam_ocrisk_API_init
  (JNIEnv *, jclass);

/*
 * Class:     org_sqteam_ocrisk_API
 * Method:    test
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sqteam_ocrisk_API_test
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
